name: Static code checkers

on:
  push:
  pull_request:

permissions: {}

jobs:
  git-review-rebase-code-check:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
      - run: mypy --install-types --non-interactive .
      - run: pyright
      - run: ruff check
      - run: flake8
